# Generated by Django 5.1.6 on 2025-04-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="profiles"),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="profiles"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="profiles"),
        ),
    ]
